# Generated by Django 4.2.7 on 2026-03-30 12:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('inside', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('matched_geozone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='geozones.geozone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
